
--1. Tìm các nhân viên làm việc ở phòng số 5
SELECT *
FROM NHANVIEN
WHERE PHG = 5

--2. Tìm các nhân viên có mức lương trên 25000
SELECT *
FROM NHANVIEN
WHERE LUONG > 25000

--3. Tìm các nhân viên có mức lương trên 65,000 ở phòng 1 hoặc các nhân viên có
--mức lương trên 70,000 ở phòng 2
SELECT *
FROM NHANVIEN
WHERE (LUONG > 25000 AND PHG = 1 ) OR ( LUONG > 30000 AND PHG = 2) 

--4. Cho biết họ tên đầy đủ của các nhân viên ở TP HCM
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'FULL NAME'
FROM NHANVIEN
WHERE DCHI LIKE '%TP HCM%'

--5. Cho biết họ tên đầy đủ của các nhân viên có họ bắt đầu bằng ký tự 'N'
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'FULL NAME'
FROM NHANVIEN
WHERE HONV LIKE 'N%'

--6. Cho biết ngày sinh và địa chỉ của nhân viên Lê Mạnh Hùng
SELECT  HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN', NGSINH, DCHI
FROM NHANVIEN
WHERE  HONV LIKE N'Lê' AND TENLOT LIKE N'Mạnh' AND TENNV LIKE N'Hùng' 

--7. Cho biết các nhân viên có năm sinh trong khoảng 1955 đến 1975
SELECT *
FROM NHANVIEN
WHERE NGSINH BETWEEN '1955-01-01' AND ' 1975-12-31' 


--8. Cho biết các nhân viên và năm sinh của nhân viên
 SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN',
		 YEAR(NGSINH) AS 'NAM SINH'
FROM NHANVIEN


--9. Cho biết các nhân viên và tuổi của nhân viên 


SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN',
		YEAR(GETDATE()) - YEAR(NGSINH) AS TUOI
FROM NHANVIEN


-- 3.1.2 Truy vấn có sử dụng phép kết
--10.Với mỗi phòng ban, cho biết tên phòng ban và địa điểm phòng
SELECT PHONGBAN.TENPHG, DIADIEM_PHG.DIADIEM
FROM PHONGBAN INNER JOIN DIADIEM_PHG ON PHONGBAN.MAPHG = DIADIEM_PHG.MAPHG

SELECT PHONGBAN.TENPHG, DIADIEM_PHG.DIADIEM
FROM PHONGBAN , DIADIEM_PHG 
WHERE PHONGBAN.MAPHG = DIADIEM_PHG.MAPHG


--11.Tìm tên những người trưởng phòng của từng phòng ban
SELECT PHONGBAN.TENPHG, NHANVIEN.TENNV
FROM PHONGBAN INNER JOIN NHANVIEN ON PHONGBAN.TRPHG = NHANVIEN.MANV

SELECT PHONGBAN.TENPHG, NHANVIEN.TENNV
FROM PHONGBAN , NHANVIEN 
WHERE PHONGBAN.TRPHG = NHANVIEN.MANV

-- 12.Tìm tên và địa chỉ của tất cả các nhân viên của phòng "Điều hành".
SELECT NHANVIEN.TENNV, NHANVIEN.DCHI
FROM NHANVIEN INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE PHONGBAN.TENPHG LIKE N'Điều hành'

SELECT NHANVIEN.TENNV, NHANVIEN.DCHI
FROM NHANVIEN, PHONGBAN 
WHERE NHANVIEN.PHG = PHONGBAN.MAPHG
AND PHONGBAN.TENPHG LIKE N'Điều hành'


-- 13.Với mỗi đề án ở Nha TRang, cho biết mã số đề án, mã số  phòng ban, họ tên và ngày
--nhận chức của trưởng phòng của phòng ban chủ trì đề án đó.

SELECT TENDA,TENPHG,HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN',NG_NHANCHUC, DDIEM_DA
FROM DEAN INNER JOIN PHONGBAN ON DEAN.PHONG = PHONGBAN.MAPHG, NHANVIEN
WHERE DEAN.PHONG=PHONGBAN.MAPHG AND PHONGBAN.TRPHG=NHANVIEN.MANV AND DEAN.DDIEM_DA LIKE '%Nha Trang%'

SELECT TENDA,TENPHG,HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN',NG_NHANCHUC, DDIEM_DA
FROM DEAN ,PHONGBAN  , NHANVIEN
WHERE DEAN.PHONG = PHONGBAN.MAPHG
AND DEAN.PHONG=PHONGBAN.MAPHG 
AND PHONGBAN.TRPHG=NHANVIEN.MANV 
AND DEAN.DDIEM_DA LIKE '%Nha Trang%'


--14.Tìm tên những nữ nhân viên và tên người thân của họ
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'HO VA TEN',TENTN,NHANVIEN.PHAI
FROM NHANVIEN INNER JOIN THANNHAN ON NHANVIEN.MANV=THANNHAN.MA_NVIEN
WHERE NHANVIEN.PHAI LIKE N'Nữ'

--15.Với mỗi nhân viên, cho biết họ tên nhân viên và họ tên người quản lý trực tiếp
--của nhân viên đó 

SELECT NV1.HONV + ' ' + NV1.TENLOT + ' ' + NV1.TENNV AS 'NQL',NV2.HONV + ' ' + NV2.TENLOT + ' ' + NV2.TENNV AS 'HOVATEN'
FROM NHANVIEN NV1 INNER JOIN NHANVIEN NV2 ON NV1.MANV=NV2.MA_NQL



--16.1.Với mỗi nhân viên, cho biết họ tên của nhân viên đó, họ tên người trưởng phòng

SELECT 
NV1.HONV + ' ' + NV1.TENLOT + ' ' + NV1.TENNV AS 'HO VA TEN NV',
NV2.HONV + ' ' + NV2.TENLOT + ' ' + NV2.TENNV AS 'HO VA TEN TRUONG PHONG'
FROM PHONGBAN P 
		INNER JOIN NHANVIEN NV1 ON NV1.PHG = P.MAPHG
		INNER JOIN NHANVIEN NV2 ON NV2.MANV = P.TRPHG


--16.2.Với mỗi nhân viên, cho biết họ tên của nhân viên đó, họ tên người trưởng phòng
--và họ tên người quản lý trực tiếp của nhân viên đó.

SELECT 
NV1.HONV + ' ' + NV1.TENLOT + ' ' + NV1.TENNV AS 'HO VA TEN NV',
NV2.HONV + ' ' + NV2.TENLOT + ' ' + NV2.TENNV AS 'HO VA TEN TRUONG PHONG',
NV3.HONV + ' ' + NV3.TENLOT + ' ' + NV3.TENNV AS 'HO VA TEN NQL'
FROM PHONGBAN P 
		INNER JOIN NHANVIEN NV1 ON NV1.PHG = P.MAPHG
		INNER JOIN NHANVIEN NV2 ON NV2.MANV = P.TRPHG
		INNER JOIN NHANVIEN NV3 ON NV3.MANV = NV1.MA_NQL

--17.Tên những nhân viên phòng số 5 có tham gia vào đề án "SẢN PHẨM X
-- và NGUYỄN THANH TÙNG quản lý trực tiếp.
SELECT NV1.HONV,NV1.TENLOT,NV1.TENNV,NV1.PHG, NV2.HONV+ ' ' + NV2.TENLOT+ ' ' + NV2.TENNV AS 'HO TEN NQL' 

FROM NHANVIEN NV1, DEAN, PHANCONG , NHANVIEN NV2
WHERE DEAN.TENDA='San pham X' 
	AND	DEAN.MADA=PHANCONG.MADA AND NV1.MANV= PHANCONG.MA_NVIEN AND
	NV1.PHG=5 AND NV1.MA_NQL=NV2.MANV AND NV2.HONV= N'Nguyễn' AND NV2.TENLOT=N'Thanh' AND NV2.TENNV=N'Tùng'














--18.Cho biết tên các đề án mà nhân viên ĐINH BÁ TIẾN đã tham gia.
	SELECT DEAN.TENDA
	FROM NHANVIEN LEFT JOIN ( PHANCONG INNER JOIN DEAN ON PHANCONG.MADA= DEAN.MADA) ON MANV=MA_NVIEN
	WHERE NHANVIEN.HONV = N'Đinh' AND NHANVIEN.TENLOT = N'Bá' AND NHANVIEN.TENNV = N'Tiên'


--19.Cho biết số lượng đề án của công ty
SELECT COUNT(*) 
FROM DEAN


--20.Cho biết số lượng đề án do phòng 'Nghiên Cứu' chủ trì
SELECT COUNT(*)
FROM DEAN , PHONGBAN
WHERE DEAN.PHONG=PHONGBAN.MAPHG AND PHONGBAN.TENPHG= N'Nghiên cứu'

SELECT COUNT(*)
FROM DEAN INNER JOIN PHONGBAN ON DEAN.PHONG=PHONGBAN.MAPHG
WHERE DEAN.PHONG=PHONGBAN.MAPHG AND PHONGBAN.TENPHG= N'Nghiên cứu'


--21.Cho biết lương trung bình của các nữ nhân viên
SELECT AVG(LUONG)
FROM NHANVIEN
WHERE	PHAI=N'Nữ'

--22.Cho biết số thân nhân của nhân viên ‘ĐINH BÁ TIẾN'
	SELECT	COUNT(*)
	FROM NHANVIEN, THANNHAN
	WHERE THANNHAN.MA_NVIEN=NHANVIEN.MANV AND NHANVIEN.HONV = N'Đinh' AND NHANVIEN.TENLOT = N'Bá' AND NHANVIEN.TENNV = N'Tiên'

	SELECT	COUNT(*)
	FROM NHANVIEN INNER JOIN THANNHAN ON THANNHAN.MA_NVIEN=NHANVIEN.MANV
	WHERE THANNHAN.MA_NVIEN=NHANVIEN.MANV AND NHANVIEN.HONV = N'Đinh' AND NHANVIEN.TENLOT = N'Bá' AND NHANVIEN.TENNV = N'Tiên'



--23.Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các
--nhân viên tham dự đề án đó.

SELECT TENDA , SUM(THOIGIAN) AS TONG_TG
FROM DEAN, PHANCONG
WHERE DEAN.MADA=PHANCONG.MADA
GROUP BY DEAN.MADA, DEAN.TENDA

SELECT TENDA , SUM(THOIGIAN) AS TONG_TG
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA=PHANCONG.MADA
WHERE DEAN.MADA=PHANCONG.MADA
GROUP BY DEAN.MADA, DEAN.TENDA



--24.Với mỗi đề án, cho biết có bao nhiêu nhân viên tham gia đề án đó
SELECT DEAN.TENDA , COUNT(*) AS SONHANVIEN
FROM PHANCONG, DEAN
WHERE PHANCONG.MADA=DEAN.MADA
GROUP BY PHANCONG.MADA,DEAN.TENDA

SELECT DEAN.TENDA , COUNT(*) AS SONHANVIEN
FROM PHANCONG INNER JOIN  DEAN ON PHANCONG.MADA=DEAN.MADA
GROUP BY PHANCONG.MADA,DEAN.TENDA

--25.Với mỗi nhân viên có số thân nhân lớn hơn 2, cho biết họ và tên nhân viên và số lượng thân nhân của nhân
--viên đó.
SELECT NHANVIEN.HONV, NHANVIEN.TENNV, COUNT (*) AS SOTN
FROM NHANVIEN INNER JOIN THANNHAN ON NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY NHANVIEN.MANV, NHANVIEN.HONV,NHANVIEN.TENNV
HAVING COUNT(*) > 2

SELECT NHANVIEN.HONV, NHANVIEN.TENNV, COUNT (*) AS SOTN
FROM NHANVIEN,THANNHAN 
WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN
GROUP BY NHANVIEN.MANV, NHANVIEN.HONV,NHANVIEN.TENNV
HAVING COUNT(*) > 2

--26.Với mỗi nhân viên, cho biết họ tên của nhân viên và số lượng đề án mà nhân
--viên đó đã tham gia.
SELECT NHANVIEN.TENNV, COUNT (*) SODEAN 
FROM NHANVIEN INNER JOIN  PHANCONG ON  NHANVIEN.MANV=PHANCONG.MA_NVIEN
GROUP BY NHANVIEN.MANV, NHANVIEN.TENNV 

SELECT NHANVIEN.TENNV, COUNT (*) SODEAN 
FROM NHANVIEN ,PHANCONG 
WHERE  NHANVIEN.MANV=PHANCONG.MA_NVIEN
GROUP BY NHANVIEN.MANV, NHANVIEN.TENNV 




--27.Với mỗi nhân viên, cho biết số lượng nhân viên mà nhân viên đó quản lý trực
--tiếp.
SELECT TENPHG ,COUNT (MANV) AS SL_NV
FROM NHANVIEN, PHONGBAN
WHERE PHG=MAPHG
GROUP BY PHG, TENPHG



--28.Với mỗi phòng ban, liệt kê tên phòng ban và lương trung bình của những nhân
--viên làm việc cho phòng ban đó.
SELECT TENPHG ,AVG(LUONG)
FROM NHANVIEN, PHONGBAN
WHERE PHG=MAPHG
GROUP BY PHG, TENPHG

SELECT TENPHG , AVG(LUONG)
FROM NHANVIEN INNER JOIN PHONGBAN ON PHG=MAPHG
GROUP BY PHG, TENPHG


--29.Với các phòng ban có mức lương trung bình trên 30,000, liệt kê tên phòng ban
--và số lượng nhân viên của phòng ban đó.
SELECT TENPHG ,COUNT (MANV) AS SL_NV
FROM NHANVIEN INNER JOIN PHONGBAN ON PHG=MAPHG
GROUP BY PHG, TENPHG
 HAVING AVG(LUONG) > 30000

SELECT TENPHG ,COUNT (MANV) AS SL_NV
FROM NHANVIEN, PHONGBAN
WHERE PHG=MAPHG
GROUP BY PHG, TENPHG
HAVING AVG(LUONG) > 30000



--30.Với mỗi phòng ban, cho biết tên phòng ban và số lượng đề án mà phòng ban đó
--chủ trì
SELECT PHONGBAN.TENPHG, COUNT (*) AS SL_DA
FROM DEAN INNER JOIN PHONGBAN ON DEAN.PHONG=PHONGBAN.MAPHG
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG

SELECT PHONGBAN.TENPHG, COUNT (* ) AS SL_DA
FROM DEAN ,PHONGBAN 
WHERE DEAN.PHONG=PHONGBAN.MAPHG
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG


--31.Với mỗi phòng ban, cho biết tên phòng ban, họ tên người trưởng phòng và số
--lượng đề án mà phòng ban đó chủ trì

SELECT PHONGBAN.TENPHG, NHANVIEN.TENNV , COUNT (*) AS SLDEAN
FROM DEAN , PHONGBAN, NHANVIEN
WHERE DEAN.PHONG=PHONGBAN.MAPHG AND PHONGBAN.TRPHG=NHANVIEN.MANV
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG, NHANVIEN.TENNV 

SELECT PHONGBAN.TENPHG, NHANVIEN.TENNV , COUNT (*) AS SLDEAN
FROM PHONGBAN
 INNER JOIN  DEAN ON DEAN.PHONG=PHONGBAN.MAPHG
 	INNER JOIN NHANVIEN ON PHONGBAN.TRPHG=NHANVIEN.MANV
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG, NHANVIEN.TENNV 


	

--32.Với mỗi phòng ban có mức lương trung bình lớn hơn 50,000, cho biết tên phòng
--ban và số lượng đề án mà phòng ban đó chủ trì.

SELECT PHONGBAN.TENPHG, COUNT (DISTINCT MADA) AS SL_DA
FROM PHONGBAN INNER JOIN DEAN ON DEAN.PHONG=PHONGBAN.MAPHG
			INNER JOIN NHANVIEN ON PHONGBAN.MAPHG=NHANVIEN.PHG
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG
HAVING AVG(LUONG) > 50000

SELECT PHONGBAN.TENPHG, COUNT (DISTINCT MADA) AS SL_DA
FROM PHONGBAN , DEAN , NHANVIEN 
WHERE	 PHONGBAN.MAPHG=NHANVIEN.PHG AND DEAN.PHONG=PHONGBAN.MAPHG
GROUP BY DEAN.PHONG, PHONGBAN.TENPHG
HAVING AVG(LUONG) > 50000




--33.Cho biết số đề án diễn ra tại từng địa điểm
SELECT DDIEM_DA, COUNT (*) AS SODEAN
FROM DEAN
GROUP BY DDIEM_DA



--34.Với mỗi đề án, cho biết tên đề án và số lượng công việc của đề án này. 
SELECT DEAN.TENDA , COUNT (*) AS SL_CV
FROM DEAN INNER JOIN CONGVIEC ON DEAN.MADA=CONGVIEC.MADA 
GROUP BY DEAN.MADA, DEAN.TENDA

SELECT DEAN.TENDA , COUNT (*) AS SL_CV
FROM DEAN , CONGVIEC 
WHERE DEAN.MADA=CONGVIEC.MADA 
GROUP BY DEAN.MADA, DEAN.TENDA



--35.Với mỗi công việc trong đề án, cho biết số lượng nhân viên
--được phân công .
SELECT DEAN.TENDA, CONGVIEC.STT , COUNT(*) AS SLNV
FROM CONGVIEC, DEAN, PHANCONG
WHERE PHANCONG.MADA= CONGVIEC.MADA AND
		PHANCONG.STT=CONGVIEC.STT AND
		CONGVIEC.MADA=DEAN.MADA 
GROUP BY CONGVIEC.MADA, CONGVIEC.STT, DEAN.TENDA

SELECT DEAN.TENDA, CONGVIEC.STT , COUNT(*) AS SLNV
FROM CONGVIEC INNER JOIN PHANCONG ON  PHANCONG.MADA= CONGVIEC.MADA AND PHANCONG.STT=CONGVIEC.STT
				INNER JOIN DEAN ON CONGVIEC.MADA=DEAN.MADA 
GROUP BY CONGVIEC.MADA, CONGVIEC.STT, DEAN.TENDA









--3.3 TRUY VẤN LỒNG + GOM NHÓM

--36.Cho biết danh sách các đề án (MADA) có: nhân công với họ (HONV) là 'Lê' hoặc
--có người trưởng phòng chủ trì đề án với họ (HONV) là 'Lê'.

SELECT MADA
FROM DEAN
WHERE MADA IN ( SELECT PHANCONG.MADA 
				FROM NHANVIEN, PHANCONG
				WHERE NHANVIEN.MANV=PHANCONG.MA_NVIEN
				AND NHANVIEN.HONV=N'Lê')
		or MADA IN(SELECT DEAN.MADA
					FROM DEAN, PHONGBAN, NHANVIEN
					WHERE NHANVIEN.MANV=PHONGBAN.TRPHG
						AND	PHONGBAN.MAPHG=DEAN.PHONG
						AND NHANVIEN.HONV=N'Lê')


--37.Danh sách những nhân viên (HONV, TENLOT, TENNV) có trên 2 thân nhân.
SELECT HONV, TENLOT,TENNV
FROM NHANVIEN
WHERE (SELECT  COUNT(*)
		FROM THANNHAN
		WHERE MA_NVIEN=MANV ) > 2


--38.Danh sách những nhân viên (HONV, TENLOT, TENNV) không có thân nhân nào
--(dùng NOT IN, LEFT JOIN, NOT EXISTS)
SELECT HONV, TENLOT,TENNV
FROM NHANVIEN
WHERE  NOT EXISTS (SELECT  *
		FROM THANNHAN
		WHERE MA_NVIEN=MANV ) 


SELECT HONV, TENLOT,TENNV
FROM NHANVIEN
WHERE (SELECT  COUNT(*)
		FROM THANNHAN
		WHERE MA_NVIEN=MANV ) = 0



--39.Danh sách những trưởng phòng (HONV, TENLOT, TENNV) có tối thiểu một thân
--nhân.
SELECT NHANVIEN.HONV , NHANVIEN.TENLOT, NHANVIEN.TENNV	
FROM PHONGBAN, NHANVIEN 
WHERE PHONGBAN.TRPHG= NHANVIEN.MANV AND EXISTS (
		SELECT *
		FROM THANNHAN
		WHERE MA_NVIEN=PHONGBAN.TRPHG)

SELECT HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE  MANV IN (SELECT TRPHG FROM PHONGBAN) AND
		MANV IN (SELECT MA_NVIEN FROM THANNHAN)



--40.Tìm họ (HONV) của những trưởng phòng chưa có gia đình.
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE  MANV IN (SELECT TRPHG FROM PHONGBAN) AND
		MANV NOT IN    (SELECT MA_NVIEN 
						FROM THANNHAN
						WHERE QUANHE=N'Vợ Chồng')



--41.Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương trên mức
--lương trung bình của phòng "Nghiên cứu"
SELECT  HONV, TENLOT, TENNV, LUONG, PHG
FROM NHANVIEN
WHERE LUONG > ANY ( SELECT NHANVIEN.LUONG
					FROM NHANVIEN, PHONGBAN
					WHERE NHANVIEN.PHG= PHONGBAN.MAPHG
					AND TENPHG=N'Nghiên cứu')	


--42.Cho biết tên phòng ban và họ tên trưởng phòng của phòng ban có đông nhân
--viên nhất.

SELECT NHANVIEN.PHG, PHONGBAN.TENPHG , COUNT(*) AS SOLUONG
FROM  NHANVIEN, PHONGBAN 
WHERE NHANVIEN.PHG= PHONGBAN.MAPHG
GROUP BY NHANVIEN.PHG, PHONGBAN.TENPHG
HAVING COUNT(*) >= ALL(
						SELECT COUNT (*)
						FROM NHANVIEN
						GROUP BY PHG)

SELECT NHANVIEN.PHG, PHONGBAN.TENPHG , COUNT(*) AS SOLUONG
FROM  NHANVIEN INNER JOIN  PHONGBAN ON NHANVIEN.PHG= PHONGBAN. MAPHG
GROUP BY NHANVIEN.PHG, PHONGBAN.TENPHG
HAVING COUNT(*) >= ALL(
						SELECT COUNT (*)
						FROM NHANVIEN
						GROUP BY PHG)



--43.Cho biết danh sách các mã đề án mà nhân viên có mã là 007 chưa làm.
SELECT MADA
FROM DEAN
WHERE NOT EXISTS ( SELECT * 
					FROM PHANCONG 
					WHERE MADA=DEAN.MADA AND	MA_NVIEN= '007')




--44.Danh sách nhân viên gồm MaNv, HovaTen (được nối từ các cột HONV, TENLOT,
--TENNV) và địa chỉ (DCHI) của những nhân viên làm việc cho một đề án ở 'TP
--HCM' nhưng phòng ban mà họ trực thuộc lại không tọa lạc ở thành phố 'TP HCM'
--.
SELECT HONV, TENLOT, TENNV, DCHI
FROM NHANVIEN 
WHERE NHANVIEN.MANV IN ( SELECT PHANCONG.MA_NVIEN
						FROM PHANCONG, DEAN 
						WHERE PHANCONG.MADA=DEAN.MADA AND DEAN.DDIEM_DA=N'TP HCM')
AND NHANVIEN.PHG NOT IN (SELECT PHONGBAN.MAPHG
						 FROM PHONGBAN, DIADIEM_PHG
						 WHERE PHONGBAN.MAPHG= DIADIEM_PHG.MAPHG AND DIADIEM=N'TP HCM')  
			



--45. Tổng quát câu 16, tìm họ tên và địa chỉ của các nhân viên làm việc cho một đề án
--ở một thành phố nhưng phòng ban mà họ trực thuộc lại không toạ lạc ở thành
--phố đó.

SELECT DISTINCT NHANVIEN.HONV, NHANVIEN.TENNV, NHANVIEN.DCHI
FROM NHANVIEN, PHONGBAN , PHANCONG , DEAN, DIADIEM_PHG
WHERE NHANVIEN.PHG= PHONGBAN.MAPHG AND DIADIEM_PHG.MAPHG= PHONGBAN.MAPHG AND 
	  PHANCONG.MA_NVIEN = NHANVIEN.MANV AND PHANCONG.MADA= DEAN.MADA AND 
	  DEAN.DDIEM_DA <> DIADIEM_PHG.DIADIEM










--3.5 COMPUTE/COMPUTE BY
--46.Danh sách nhân viên gồm MaNv, HovaTen (được nối từ các cột HONV, TENLOT,
--TENNV), Tuổi và tuổi trung bình của các nhân viên trong công ty (dùng
--COMPUTE)
--47.Danh sách các Phòng ban, Tên đề án và tổng lương trung bình phải trả cho mỗi
--đề án (COMPUTE BY). Lương trung bình được tính từ trung bình của tổng
--lương_đề án các nhân viên, trong đó lương_đề án của mỗi nhân viên = LUONGx
--với số giờ làm việc cho mỗi đề án của nhân viên đó.
--3.4 PHÉP CHIA
--48.Danh sách những nhân viên MaNV, Phái, HoTen được nối từ HONV, TENLOT,
--TENNV làm việc trong mọi đề án của công ty
--49.Danh sách những nhân viên MaNV, Phái, HoTen được nối từ HONV, TENLOT,
--TENNV được phân công tất cả đề án do phòng số 5 chủ trì.
--50.Tìm những nhân viên MaNV, Phái, HoTen (HONV, TENLOT, TENNV) được phân
--công tất cả đề án mà nhân viên Lê Minh Tính làm việc
--51.Cho biết danh sách nhân viên tham gia vào tất cả các đề án ở TP HCM
--52.Cho biết phòng ban chủ trì tất cả các đề án ở HaNoi
--3.6. UNION/INTERSECT
--53.Cho biết những phòng ban có nhân viên tham gia cả 2 dự án ở HaNoi và Tp.HCM.
--54. Cho biết những phòng ban có nhân viên tham gia dự án ở Tp.HCM hoặc ở HaNoi.

 